name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # You can adjust the version as needed
      - name: Install dependencies
        run: npm ci --force
        
      - name: Start Server
        run: npm start &
        
      - name: Run Cypress tests
        run: npm run cypress:run
